// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j72Avb9ZCpnuWkUKURgspB
// Component: BEPqn7HR6hE
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import TextInput from "../../TextInput"; // plasmic-import: czIRwjWa6P2/component
import Button from "../../Button"; // plasmic-import: bsHYMTqsewT/component
import { useScreenVariants as useScreenVariantsaE5I9AyA2Unvu } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: aE5i9AyA2unvu/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_wedding.module.css"; // plasmic-import: j72Avb9ZCpnuWkUKURgspB/projectcss
import sty from "./PlasmicPrincipal.module.css"; // plasmic-import: BEPqn7HR6hE/css
import LetrasIcon from "./icons/PlasmicIcon__Letras"; // plasmic-import: YLk2j-ZmcQ6/icon
import FloresIcon from "./icons/PlasmicIcon__Flores"; // plasmic-import: kSeAGTBe8H7/icon
import Polygon6Icon from "./icons/PlasmicIcon__Polygon6"; // plasmic-import: 6YmzTPpOhex/icon
import Rings2Icon from "./icons/PlasmicIcon__Rings2"; // plasmic-import: z3BnojU3NyM/icon
import Copa2Icon from "./icons/PlasmicIcon__Copa2"; // plasmic-import: -phooncCvyR/icon
import Cena2Icon from "./icons/PlasmicIcon__Cena2"; // plasmic-import: KqPlEmsKEku/icon
import Bola2Icon from "./icons/PlasmicIcon__Bola2"; // plasmic-import: 4A559WGKOi7/icon
import Vector17Icon from "./icons/PlasmicIcon__Vector17"; // plasmic-import: JKyEDg31S3T/icon
import Vector18Icon from "./icons/PlasmicIcon__Vector18"; // plasmic-import: va7yLc0aKda/icon
import Line5Icon from "./icons/PlasmicIcon__Line5"; // plasmic-import: c865p2zkfbQ/icon
import Line6Icon from "./icons/PlasmicIcon__Line6"; // plasmic-import: Wk8xqNmmVhK/icon
import Vector15Icon from "./icons/PlasmicIcon__Vector15"; // plasmic-import: 4N01F37ufcu/icon
import Vector16Icon from "./icons/PlasmicIcon__Vector16"; // plasmic-import: IxXbNq6loq8/icon
import CopaIcon from "./icons/PlasmicIcon__Copa"; // plasmic-import: MCcUz9ZLVF1/icon
import CenaIcon from "./icons/PlasmicIcon__Cena"; // plasmic-import: PjrIv_sUJcV/icon
import BolaIcon from "./icons/PlasmicIcon__Bola"; // plasmic-import: bA8skHVm69t/icon
import WalletTracedIcon from "./icons/PlasmicIcon__WalletTraced"; // plasmic-import: ef38l5rGTjP/icon
import Ellipse1Icon from "./icons/PlasmicIcon__Ellipse1"; // plasmic-import: zGZjcbACVmL/icon
import TrazoMapa1TracedIcon from "./icons/PlasmicIcon__TrazoMapa1Traced"; // plasmic-import: vIB1zg7bYuR/icon
import UnionIcon from "./icons/PlasmicIcon__Union"; // plasmic-import: XF_eT3LVgni/icon
import RingsIcon from "./icons/PlasmicIcon__Rings"; // plasmic-import: 6Wz3Xy-RSTw/icon
import GasStationTracedIcon from "./icons/PlasmicIcon__GasStationTraced"; // plasmic-import: c2GIKsZ-vSG/icon
import vector3KiK5TbFXkxd from "./images/vector3.svg"; // plasmic-import: KiK5TbFXkxd/picture
import vector2C2N1ZhuBzEz from "./images/vector2.svg"; // plasmic-import: C2n1zhuBzEz/picture
import vector4Oie5VjFkKt from "./images/vector4.svg"; // plasmic-import: OIE5VjFkKt/picture
import capturaDePantalla20220513ALas21151Traced26Esz4J9BrR from "./images/capturaDePantalla20220513ALas21151Traced2.svg"; // plasmic-import: 6ESZ4J9BrR/picture
import vector0NKdD7ATsPk from "./images/vector.svg"; // plasmic-import: 0NKdD7ATsPk/picture
import capturaDePantalla20220513ALas21151TracedHKAlucLm6Nq from "./images/capturaDePantalla20220513ALas21151Traced.svg"; // plasmic-import: hKAlucLm6Nq/picture
import imageAfdupae1 from "./images/image.jpeg"; // plasmic-import: AFDUPAE_1/picture

export const PlasmicPrincipal__VariantProps = new Array();

export const PlasmicPrincipal__ArgProps = new Array();

function PlasmicPrincipal__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = Object.assign({}, props.args);
  const $props = args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsaE5I9AyA2Unvu()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        {true ? (
          <div
            data-plasmic-name={"root"}
            data-plasmic-override={overrides.root}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              projectcss.plasmic_tokens,
              sty.root
            )}
          >
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__e7HIw)}>
                <div
                  data-plasmic-name={"home2"}
                  data-plasmic-override={overrides.home2}
                  className={classNames(projectcss.all, sty.home2)}
                >
                  <LetrasIcon
                    className={classNames(projectcss.all, sty.svg__lVNeH)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"fondo"}
                    data-plasmic-override={overrides.fondo}
                    className={classNames(projectcss.all, sty.fondo)}
                  >
                    <div
                      data-plasmic-name={"mask2"}
                      data-plasmic-override={overrides.mask2}
                      className={classNames(projectcss.all, sty.mask2)}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__na5Y
                      )}
                    >
                      {"Nasim  &   Paul"}
                    </div>
                  </div>
                </div>

                <div
                  data-plasmic-name={"loveHistory"}
                  data-plasmic-override={overrides.loveHistory}
                  className={classNames(projectcss.all, sty.loveHistory)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox___7G8T)}
                  >
                    <div
                      data-plasmic-name={"layer12"}
                      data-plasmic-override={overrides.layer12}
                      className={classNames(projectcss.all, sty.layer12)}
                    />
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__o6TUq)}
                    displayHeight={"215px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"169px"}
                    loading={"lazy"}
                    src={{
                      src: vector3KiK5TbFXkxd,
                      fullWidth: 169,
                      fullHeight: 215,
                      aspectRatio: 0.786047
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__tqh6W)}
                    displayHeight={"215px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"169px"}
                    loading={"lazy"}
                    src={{
                      src: vector2C2N1ZhuBzEz,
                      fullWidth: 169,
                      fullHeight: 215,
                      aspectRatio: 0.786047
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__xj4DC)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4R5EV
                      )}
                    >
                      {"Nuestra historia"}
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__nxe2E)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jHFrA
                      )}
                    >
                      {
                        "Nos conocimos hace unos 5 bailando y algo en nuestros corazones se activó, pero Dios quiso darnos más tiempo para que hace 1 año y 5 meses, nos volviésemos a reencontrar y en muy poco tiempo nos dimos cuenta de que queríamos compartir el resto de nuestras vidas juntos.\n\nDe común acuerdo y en plena posesión de nuestras facultades mentales (sean las que sean) hemos decidido… ¡casarnos!😁"
                      }
                    </div>
                  </div>
                </div>

                <div
                  data-plasmic-name={"counter"}
                  data-plasmic-override={overrides.counter}
                  className={classNames(projectcss.all, sty.counter)}
                >
                  <FloresIcon
                    className={classNames(projectcss.all, sty.svg___1CJhG)}
                    role={"img"}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__aEr1T)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fuQvM
                        )}
                      >
                        {"29 de Octubre 2022"}
                      </div>

                      <div
                        data-plasmic-name={"fincaMiravalleGuadarrama2"}
                        data-plasmic-override={
                          overrides.fincaMiravalleGuadarrama2
                        }
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.fincaMiravalleGuadarrama2
                        )}
                      >
                        {"Finca Miravalle, Guadarrama "}
                      </div>

                      {true ? (
                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"numbers"}
                          data-plasmic-override={overrides.numbers}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.numbers)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__hzHbg
                            )}
                          >
                            {"00"}
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___71J1H
                            )}
                          >
                            {"00"}
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__i7Im9
                            )}
                          >
                            {"00"}
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___5PIfN
                            )}
                          >
                            {"00"}
                          </div>
                        </p.Stack>
                      ) : null}
                      {true ? (
                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"letters"}
                          data-plasmic-override={overrides.letters}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.letters)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__hMtY
                            )}
                          >
                            {"DÍAS"}
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__cGp4L
                            )}
                          >
                            {"HORAS"}
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__texTl
                            )}
                          >
                            {"MINUTOS"}
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___9ISi
                            )}
                          >
                            {"SEGUNDOS"}
                          </div>
                        </p.Stack>
                      ) : null}
                    </div>
                  ) : null}
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  ) ? (
                    <Polygon6Icon
                      data-plasmic-name={"left1"}
                      data-plasmic-override={overrides.left1}
                      className={classNames(projectcss.all, sty.left1)}
                      role={"img"}
                    />
                  ) : null}

                  <Polygon6Icon
                    data-plasmic-name={"r1"}
                    data-plasmic-override={overrides.r1}
                    className={classNames(projectcss.all, sty.r1)}
                    role={"img"}
                  />

                  {true ? (
                    <Polygon6Icon
                      data-plasmic-name={"r2"}
                      data-plasmic-override={overrides.r2}
                      className={classNames(projectcss.all, sty.r2)}
                      role={"img"}
                    />
                  ) : null}

                  <FloresIcon
                    className={classNames(projectcss.all, sty.svg__oIaS6)}
                    role={"img"}
                  />

                  <Polygon6Icon
                    data-plasmic-name={"left3"}
                    data-plasmic-override={overrides.left3}
                    className={classNames(projectcss.all, sty.left3)}
                    role={"img"}
                  />
                </div>

                <div
                  data-plasmic-name={"cronograma"}
                  data-plasmic-override={overrides.cronograma}
                  className={classNames(projectcss.all, sty.cronograma)}
                >
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  ) ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__wlhjd)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gtjQp
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "¿Cómo va a ser\nnuestro día?"
                          : "¿Cómo va a ser\nnuestro día?"}
                      </div>
                    </div>
                  ) : null}
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : false
                  ) ? (
                    <div
                      data-plasmic-name={"rama17"}
                      data-plasmic-override={overrides.rama17}
                      className={classNames(projectcss.all, sty.rama17)}
                    />
                  ) : null}
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : false
                  ) ? (
                    <div
                      data-plasmic-name={"homeTimetable"}
                      data-plasmic-override={overrides.homeTimetable}
                      className={classNames(projectcss.all, sty.homeTimetable)}
                    >
                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__fNxJt)}
                          displayHeight={"36px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"44px"}
                          loading={"lazy"}
                          src={{
                            src: vector4Oie5VjFkKt,
                            fullWidth: 44,
                            fullHeight: 36,
                            aspectRatio: 1.222222
                          }}
                        />
                      ) : null}
                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__fileJ)}
                          displayHeight={"36px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"50px"}
                          loading={"lazy"}
                          src={{
                            src: capturaDePantalla20220513ALas21151Traced26Esz4J9BrR,
                            fullWidth: 50,
                            fullHeight: 36,
                            aspectRatio: 1.388889
                          }}
                        />
                      ) : null}

                      <Rings2Icon
                        className={classNames(projectcss.all, sty.svg__vA3V)}
                        role={"img"}
                      />

                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <Copa2Icon
                          className={classNames(projectcss.all, sty.svg__hrP5K)}
                          role={"img"}
                        />
                      ) : null}
                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <Cena2Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___3Kwta
                          )}
                          role={"img"}
                        />
                      ) : null}
                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <Bola2Icon
                          className={classNames(projectcss.all, sty.svg__qVhCl)}
                          role={"img"}
                        />
                      ) : null}

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fjqXo
                        )}
                      >
                        {"00h"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__a02G
                        )}
                      >
                        {"00h"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wl2Hs
                        )}
                      >
                        {"00h"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ijPqC
                        )}
                      >
                        {"00h"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jF0H
                        )}
                      >
                        {"00h"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nrl96
                        )}
                      >
                        {"00h"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5KxkS
                        )}
                      >
                        {"Te podrás guapísimx"}
                      </div>

                      <div
                        data-plasmic-name={"yaEstarasAparcado3"}
                        data-plasmic-override={overrides.yaEstarasAparcado3}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.yaEstarasAparcado3
                        )}
                      >
                        {"Ya estarás aparcado "}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zzyU
                        )}
                      >
                        {"¡La ceremonia!"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__a9K5M
                        )}
                      >
                        {"Cocktail"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nKjmi
                        )}
                      >
                        {"Cena"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jy9Ik
                        )}
                      >
                        {"¡A bailar!"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pyLnM
                        )}
                      >
                        {
                          "Ponte la ropa que más te guste y te haga feliz, ¡¡pero en chándal no!! 😜"
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___694Xf
                        )}
                      >
                        {"Intenta ser puntual para no perderte nada. "}
                      </div>

                      <div
                        data-plasmic-name={
                          "loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt3"
                        }
                        data-plasmic-override={
                          overrides.loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt3
                        }
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt3
                        )}
                      >
                        {"Compartiremos juntos nuestra unión."}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bLxSn
                        )}
                      >
                        {"¡A alimentarse y compartir!"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jDmN2
                        )}
                      >
                        {
                          "Para que puedas salir rodando a la siguiente actividad."
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xpagi
                        )}
                      >
                        {
                          "Prepárate para no dejar de mover ese cuerpo y darlo todo!"
                        }
                      </div>

                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <Vector17Icon
                          className={classNames(projectcss.all, sty.svg__pQcta)}
                          role={"img"}
                        />
                      ) : null}
                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <Vector17Icon
                          className={classNames(projectcss.all, sty.svg__l5Bp)}
                          role={"img"}
                        />
                      ) : null}
                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <Vector17Icon
                          className={classNames(projectcss.all, sty.svg__fyB1P)}
                          role={"img"}
                        />
                      ) : null}
                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <Vector17Icon
                          className={classNames(projectcss.all, sty.svg__tou7B)}
                          role={"img"}
                        />
                      ) : null}
                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <Vector17Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___8Mwhx
                          )}
                          role={"img"}
                        />
                      ) : null}
                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <Vector17Icon
                          className={classNames(projectcss.all, sty.svg__n87Yi)}
                          role={"img"}
                        />
                      ) : null}
                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <Vector18Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___93R0Z
                          )}
                          role={"img"}
                        />
                      ) : null}
                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <Line5Icon
                          className={classNames(projectcss.all, sty.svg__hUlEk)}
                          role={"img"}
                        />
                      ) : null}
                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <Line6Icon
                          className={classNames(projectcss.all, sty.svg__t98Wd)}
                          role={"img"}
                        />
                      ) : null}

                      <div
                        data-plasmic-name={"rama25"}
                        data-plasmic-override={overrides.rama25}
                        className={classNames(projectcss.all, sty.rama25)}
                      />

                      <div
                        data-plasmic-name={"flor25"}
                        data-plasmic-override={overrides.flor25}
                        className={classNames(projectcss.all, sty.flor25)}
                      />

                      <div
                        data-plasmic-name={"rama15"}
                        data-plasmic-override={overrides.rama15}
                        className={classNames(projectcss.all, sty.rama15)}
                      />

                      <div
                        data-plasmic-name={"flor26"}
                        data-plasmic-override={overrides.flor26}
                        className={classNames(projectcss.all, sty.flor26)}
                      />

                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <Polygon6Icon
                          data-plasmic-name={"left2"}
                          data-plasmic-override={overrides.left2}
                          className={classNames(projectcss.all, sty.left2)}
                          role={"img"}
                        />
                      ) : null}
                    </div>
                  ) : null}
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  ) ? (
                    <div
                      data-plasmic-name={"rama14"}
                      data-plasmic-override={overrides.rama14}
                      className={classNames(projectcss.all, sty.rama14)}
                    />
                  ) : null}
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  ) ? (
                    <div
                      data-plasmic-name={"flor23"}
                      data-plasmic-override={overrides.flor23}
                      className={classNames(projectcss.all, sty.flor23)}
                    />
                  ) : null}
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  ) ? (
                    <div
                      data-plasmic-name={"frame17"}
                      data-plasmic-override={overrides.frame17}
                      className={classNames(projectcss.all, sty.frame17)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__cJ64U
                        )}
                      >
                        {"00h"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3SUFr
                        )}
                      >
                        {"00h"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hb3Ae
                        )}
                      >
                        {"00h"}
                      </div>

                      <Vector15Icon
                        className={classNames(projectcss.all, sty.svg___0HW4Z)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fAQdb
                        )}
                      >
                        {"Te podrás guapísimx"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gVbNb
                        )}
                      >
                        {"¡La ceremonia!"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9FUgb
                        )}
                      >
                        {"Cena"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__l4F1K
                        )}
                      >
                        {
                          "Ponte la ropa que más te guste y te haga feliz, ¡¡pero en chándal no!! 😜"
                        }
                      </div>

                      <div
                        data-plasmic-name={
                          "loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt2"
                        }
                        data-plasmic-override={
                          overrides.loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt2
                        }
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt2
                        )}
                      >
                        {"Compartiremos juntos nuestra unión."}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oJyde
                        )}
                      >
                        {
                          "Para que puedas salir rodando a la siguiente actividad."
                        }
                      </div>

                      <Vector16Icon
                        className={classNames(projectcss.all, sty.svg___47Lw)}
                        role={"img"}
                      />

                      <Vector16Icon
                        className={classNames(projectcss.all, sty.svg__dS01)}
                        role={"img"}
                      />

                      <Vector16Icon
                        className={classNames(projectcss.all, sty.svg__d5Egg)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xa7LD
                        )}
                      >
                        {"00h"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__cIdk3
                        )}
                      >
                        {"00h"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__umJjH
                        )}
                      >
                        {"00h"}
                      </div>

                      <div
                        data-plasmic-name={"yaEstarasAparcado2"}
                        data-plasmic-override={overrides.yaEstarasAparcado2}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.yaEstarasAparcado2
                        )}
                      >
                        {"Ya estarás aparcado "}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tXytF
                        )}
                      >
                        {"Cocktail"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kj5Fa
                        )}
                      >
                        {"¡A bailar! "}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oV11F
                        )}
                      >
                        {"Intenta ser puntual para no perderte nada. "}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__r9TA
                        )}
                      >
                        {"¡A alimentarse y compartir!"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pHpuh
                        )}
                      >
                        {
                          "Prepárate para no dejar de mover ese cuerpo y darlo todo!"
                        }
                      </div>

                      <Vector16Icon
                        className={classNames(projectcss.all, sty.svg__plXzp)}
                        role={"img"}
                      />

                      <Vector16Icon
                        className={classNames(projectcss.all, sty.svg__jstMo)}
                        role={"img"}
                      />

                      <Vector16Icon
                        className={classNames(projectcss.all, sty.svg___9E0Az)}
                        role={"img"}
                      />

                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__arUj9)}
                        displayHeight={"50px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"52px"}
                        loading={"lazy"}
                        src={{
                          src: vector0NKdD7ATsPk,
                          fullWidth: 52,
                          fullHeight: 50,
                          aspectRatio: 1.04
                        }}
                      />

                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__bwgGt)}
                        displayHeight={"39px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"46px"}
                        loading={"lazy"}
                        src={{
                          src: capturaDePantalla20220513ALas21151TracedHKAlucLm6Nq,
                          fullWidth: 46,
                          fullHeight: 39,
                          aspectRatio: 1.179487
                        }}
                      />

                      <Rings2Icon
                        className={classNames(projectcss.all, sty.svg__rzdG)}
                        role={"img"}
                      />

                      <CopaIcon
                        className={classNames(projectcss.all, sty.svg__mh89K)}
                        role={"img"}
                      />

                      <CenaIcon
                        className={classNames(projectcss.all, sty.svg__fnQr9)}
                        role={"img"}
                      />

                      <BolaIcon
                        className={classNames(projectcss.all, sty.svg__wkmhR)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dWwOc
                        )}
                      >
                        {"¿Cómo va a ser \nnuestro día?"}
                      </div>

                      <div
                        data-plasmic-name={"rama24"}
                        data-plasmic-override={overrides.rama24}
                        className={classNames(projectcss.all, sty.rama24)}
                      />
                    </div>
                  ) : null}
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  ) ? (
                    <div
                      data-plasmic-name={"rama13"}
                      data-plasmic-override={overrides.rama13}
                      className={classNames(projectcss.all, sty.rama13)}
                    />
                  ) : null}
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  ) ? (
                    <div
                      data-plasmic-name={"flor24"}
                      data-plasmic-override={overrides.flor24}
                      className={classNames(projectcss.all, sty.flor24)}
                    />
                  ) : null}
                </div>

                <div
                  data-plasmic-name={"money"}
                  data-plasmic-override={overrides.money}
                  className={classNames(projectcss.all, sty.money)}
                >
                  {true ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___7Za1R
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gn4TC
                        )}
                      >
                        {"Si quieres ayudarnos"}
                      </div>

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__irZlt
                          )}
                        >
                          <WalletTracedIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___8E2Rd
                            )}
                            role={"img"}
                          />

                          <div
                            data-plasmic-name={"fincaMiravalleGuadarrama3"}
                            data-plasmic-override={
                              overrides.fincaMiravalleGuadarrama3
                            }
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.fincaMiravalleGuadarrama3
                            )}
                          >
                            {"ES22 0182 5322 2802 0000 4529"}
                          </div>
                        </div>
                      ) : null}
                    </div>
                  ) : null}

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yjwYf
                    )}
                  >
                    {
                      "Vuestra presencia en la boda será nuestro mayor regalo, pero si queréis apoyarnos con nuestra próxima aventura, aquí tenéis el lugar"
                    }
                  </div>
                </div>

                <div
                  data-plasmic-name={"confirmacion"}
                  data-plasmic-override={overrides.confirmacion}
                  className={classNames(projectcss.all, sty.confirmacion)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__zGw6G)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__u0VaC)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fZA5
                        )}
                      >
                        {"¿Te vienes?"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qr1Ru
                        )}
                      >
                        {
                          "Hay momentos en la vida que son especiales por si mismos, pero compartirlo con vosotros lo hará inolvidable. Nos encantaría que nos acompañases a celebrar nuestro enlace matrimonial. \nSi es así, escribe aquí tu nombre y cuéntanos si eres intolerante/alérgico o cualquier otro comentario que te apetezca hacernos: "
                        }
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__vgIf4)}
                    >
                      <TextInput
                        data-plasmic-name={"textInput"}
                        data-plasmic-override={overrides.textInput}
                        className={classNames("__wab_instance", sty.textInput)}
                        placeholder={""}
                      />

                      <Button
                        data-plasmic-name={"button"}
                        data-plasmic-override={overrides.button}
                        className={classNames("__wab_instance", sty.button)}
                      >
                        {"Confirmo!"}
                      </Button>
                    </div>
                  </div>
                </div>

                <div
                  data-plasmic-name={"direccion"}
                  data-plasmic-override={overrides.direccion}
                  className={classNames(projectcss.all, sty.direccion)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox___3SaVo)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__r1Mlq)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__poGpP
                        )}
                      >
                        {"Como llegar"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__x2Y3F
                        )}
                      >
                        {
                          "Carretera de la Coruña, km 44.\n\n28440 GUADARRAMA (MADRID).\n\nMiravalle está escasamente a 20 minutos de Madrid, por la Autopista de la Coruña A-6 (Salida-42), en el Km. 44 y a 8 minutos del Real Sitio de San Lorenzo de El Escorial.\n\nSe sitúa entre los municipios de Collado Villalba y Guadarrama.\n\nSi sigues en duda de cómo llegar, puedes pinchar en el mapa y que tú GPS te lleve 😄"
                        }
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__p99Us)}
                    >
                      <a
                        data-plasmic-name={"link"}
                        data-plasmic-override={overrides.link}
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link
                        )}
                        href={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "https://goo.gl/maps/1TpZ7KfnWpXACfnB6"
                            : "https://goo.gl/maps/1TpZ7KfnWpXACfnB6"
                        }
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__umrGr)}
                          displayHeight={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "auto"
                              : "100%"
                          }
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "auto"
                              : "auto"
                          }
                          link={"https://goo.gl/maps/1TpZ7KfnWpXACfnB6"}
                          loading={"lazy"}
                          src={{
                            src: imageAfdupae1,
                            fullWidth: 1284,
                            fullHeight: 1283,
                            aspectRatio: undefined
                          }}
                        />
                      </a>

                      {true ? (
                        <div
                          data-plasmic-name={"map2"}
                          data-plasmic-override={overrides.map2}
                          className={classNames(projectcss.all, sty.map2)}
                        >
                          <div
                            data-plasmic-name={
                              "capturaDePantalla20220511ALas21132"
                            }
                            data-plasmic-override={
                              overrides.capturaDePantalla20220511ALas21132
                            }
                            className={classNames(
                              projectcss.all,
                              sty.capturaDePantalla20220511ALas21132
                            )}
                          />

                          <Ellipse1Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__rb4Pb
                            )}
                            role={"img"}
                          />

                          <TrazoMapa1TracedIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__k9Ki
                            )}
                            role={"img"}
                          />

                          <UnionIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___3AqaK
                            )}
                            role={"img"}
                          />

                          <RingsIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__xsAy
                            )}
                            role={"img"}
                          />

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"frame18"}
                            data-plasmic-override={overrides.frame18}
                            hasGap={true}
                            className={classNames(projectcss.all, sty.frame18)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__k0JbU
                              )}
                            >
                              {"M-527"}
                            </div>
                          </p.Stack>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"frame19"}
                            data-plasmic-override={overrides.frame19}
                            hasGap={true}
                            className={classNames(projectcss.all, sty.frame19)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___9I6QE
                              )}
                            >
                              {"M-620"}
                            </div>
                          </p.Stack>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"frame20"}
                            data-plasmic-override={overrides.frame20}
                            hasGap={true}
                            className={classNames(projectcss.all, sty.frame20)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__p9WD
                              )}
                            >
                              {"M-510"}
                            </div>
                          </p.Stack>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"frame21"}
                            data-plasmic-override={overrides.frame21}
                            hasGap={true}
                            className={classNames(projectcss.all, sty.frame21)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__g6Vpw
                              )}
                            >
                              {"M-619"}
                            </div>
                          </p.Stack>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"frame22"}
                            data-plasmic-override={overrides.frame22}
                            hasGap={true}
                            className={classNames(projectcss.all, sty.frame22)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__eXtld
                              )}
                            >
                              {"AP-6"}
                            </div>
                          </p.Stack>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"frame23"}
                            data-plasmic-override={overrides.frame23}
                            hasGap={true}
                            className={classNames(projectcss.all, sty.frame23)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__wjq87
                              )}
                            >
                              {"AP-6"}
                            </div>
                          </p.Stack>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"frame24"}
                            data-plasmic-override={overrides.frame24}
                            hasGap={true}
                            className={classNames(projectcss.all, sty.frame24)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__c5Lh5
                              )}
                            >
                              {"N-VI"}
                            </div>
                          </p.Stack>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"frame25"}
                            data-plasmic-override={overrides.frame25}
                            hasGap={true}
                            className={classNames(projectcss.all, sty.frame25)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ztti7
                              )}
                            >
                              {"N-VI"}
                            </div>
                          </p.Stack>

                          <GasStationTracedIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__gLsS
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                    </div>
                  </div>
                </div>
              </div>
            ) : null}
          </div>
        ) : null}
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "home2",
    "fondo",
    "mask2",
    "loveHistory",
    "layer12",
    "counter",
    "fincaMiravalleGuadarrama2",
    "numbers",
    "letters",
    "left1",
    "r1",
    "r2",
    "left3",
    "cronograma",
    "rama17",
    "homeTimetable",
    "yaEstarasAparcado3",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt3",
    "rama25",
    "flor25",
    "rama15",
    "flor26",
    "left2",
    "rama14",
    "flor23",
    "frame17",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt2",
    "yaEstarasAparcado2",
    "rama24",
    "rama13",
    "flor24",
    "money",
    "fincaMiravalleGuadarrama3",
    "confirmacion",
    "textInput",
    "textbox",
    "button",
    "direccion",
    "link",
    "map2",
    "capturaDePantalla20220511ALas21132",
    "frame18",
    "frame19",
    "frame20",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "frame25"
  ],

  home2: ["home2", "fondo", "mask2"],
  fondo: ["fondo", "mask2"],
  mask2: ["mask2"],
  loveHistory: ["loveHistory", "layer12"],
  layer12: ["layer12"],
  counter: [
    "counter",
    "fincaMiravalleGuadarrama2",
    "numbers",
    "letters",
    "left1",
    "r1",
    "r2",
    "left3"
  ],

  fincaMiravalleGuadarrama2: ["fincaMiravalleGuadarrama2"],
  numbers: ["numbers"],
  letters: ["letters"],
  left1: ["left1"],
  r1: ["r1"],
  r2: ["r2"],
  left3: ["left3"],
  cronograma: [
    "cronograma",
    "rama17",
    "homeTimetable",
    "yaEstarasAparcado3",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt3",
    "rama25",
    "flor25",
    "rama15",
    "flor26",
    "left2",
    "rama14",
    "flor23",
    "frame17",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt2",
    "yaEstarasAparcado2",
    "rama24",
    "rama13",
    "flor24"
  ],

  rama17: ["rama17"],
  homeTimetable: [
    "homeTimetable",
    "yaEstarasAparcado3",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt3",
    "rama25",
    "flor25",
    "rama15",
    "flor26",
    "left2"
  ],

  yaEstarasAparcado3: ["yaEstarasAparcado3"],
  loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt3:
    [
      "loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt3"
    ],

  rama25: ["rama25"],
  flor25: ["flor25"],
  rama15: ["rama15"],
  flor26: ["flor26"],
  left2: ["left2"],
  rama14: ["rama14"],
  flor23: ["flor23"],
  frame17: [
    "frame17",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt2",
    "yaEstarasAparcado2",
    "rama24"
  ],

  loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt2:
    [
      "loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt2"
    ],

  yaEstarasAparcado2: ["yaEstarasAparcado2"],
  rama24: ["rama24"],
  rama13: ["rama13"],
  flor24: ["flor24"],
  money: ["money", "fincaMiravalleGuadarrama3"],
  fincaMiravalleGuadarrama3: ["fincaMiravalleGuadarrama3"],
  confirmacion: ["confirmacion", "textInput", "textbox", "button"],
  textInput: ["textInput", "textbox"],
  button: ["button"],
  direccion: [
    "direccion",
    "link",
    "map2",
    "capturaDePantalla20220511ALas21132",
    "frame18",
    "frame19",
    "frame20",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "frame25"
  ],

  link: ["link"],
  map2: [
    "map2",
    "capturaDePantalla20220511ALas21132",
    "frame18",
    "frame19",
    "frame20",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "frame25"
  ],

  capturaDePantalla20220511ALas21132: ["capturaDePantalla20220511ALas21132"],
  frame18: ["frame18"],
  frame19: ["frame19"],
  frame20: ["frame20"],
  frame21: ["frame21"],
  frame22: ["frame22"],
  frame23: ["frame23"],
  frame24: ["frame24"],
  frame25: ["frame25"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPrincipal__ArgProps,
      internalVariantPropNames: PlasmicPrincipal__VariantProps
    });

    return PlasmicPrincipal__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPrincipal";
  } else {
    func.displayName = `PlasmicPrincipal.${nodeName}`;
  }
  return func;
}

export const PlasmicPrincipal = Object.assign(
  // Top-level PlasmicPrincipal renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    home2: makeNodeComponent("home2"),
    fondo: makeNodeComponent("fondo"),
    mask2: makeNodeComponent("mask2"),
    loveHistory: makeNodeComponent("loveHistory"),
    layer12: makeNodeComponent("layer12"),
    counter: makeNodeComponent("counter"),
    fincaMiravalleGuadarrama2: makeNodeComponent("fincaMiravalleGuadarrama2"),
    numbers: makeNodeComponent("numbers"),
    letters: makeNodeComponent("letters"),
    left1: makeNodeComponent("left1"),
    r1: makeNodeComponent("r1"),
    r2: makeNodeComponent("r2"),
    left3: makeNodeComponent("left3"),
    cronograma: makeNodeComponent("cronograma"),
    rama17: makeNodeComponent("rama17"),
    homeTimetable: makeNodeComponent("homeTimetable"),
    yaEstarasAparcado3: makeNodeComponent("yaEstarasAparcado3"),
    loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt3:
      makeNodeComponent(
        "loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt3"
      ),

    rama25: makeNodeComponent("rama25"),
    flor25: makeNodeComponent("flor25"),
    rama15: makeNodeComponent("rama15"),
    flor26: makeNodeComponent("flor26"),
    left2: makeNodeComponent("left2"),
    rama14: makeNodeComponent("rama14"),
    flor23: makeNodeComponent("flor23"),
    frame17: makeNodeComponent("frame17"),
    loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt2:
      makeNodeComponent(
        "loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt2"
      ),

    yaEstarasAparcado2: makeNodeComponent("yaEstarasAparcado2"),
    rama24: makeNodeComponent("rama24"),
    rama13: makeNodeComponent("rama13"),
    flor24: makeNodeComponent("flor24"),
    money: makeNodeComponent("money"),
    fincaMiravalleGuadarrama3: makeNodeComponent("fincaMiravalleGuadarrama3"),
    confirmacion: makeNodeComponent("confirmacion"),
    textInput: makeNodeComponent("textInput"),
    button: makeNodeComponent("button"),
    direccion: makeNodeComponent("direccion"),
    link: makeNodeComponent("link"),
    map2: makeNodeComponent("map2"),
    capturaDePantalla20220511ALas21132: makeNodeComponent(
      "capturaDePantalla20220511ALas21132"
    ),

    frame18: makeNodeComponent("frame18"),
    frame19: makeNodeComponent("frame19"),
    frame20: makeNodeComponent("frame20"),
    frame21: makeNodeComponent("frame21"),
    frame22: makeNodeComponent("frame22"),
    frame23: makeNodeComponent("frame23"),
    frame24: makeNodeComponent("frame24"),
    frame25: makeNodeComponent("frame25"),
    // Metadata about props expected for PlasmicPrincipal
    internalVariantProps: PlasmicPrincipal__VariantProps,
    internalArgProps: PlasmicPrincipal__ArgProps
  }
);

export default PlasmicPrincipal;
/* prettier-ignore-end */
