// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j72Avb9ZCpnuWkUKURgspB
// Component: qn5TLnBE3O
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_wedding.module.css"; // plasmic-import: j72Avb9ZCpnuWkUKURgspB/projectcss
import sty from "./PlasmicHomepage2.module.css"; // plasmic-import: qn5TLnBE3O/css
import LetrasIcon from "./icons/PlasmicIcon__Letras"; // plasmic-import: YLk2j-ZmcQ6/icon
import Group1Icon from "./icons/PlasmicIcon__Group1"; // plasmic-import: 0EyqZkktOVL/icon
import Polygon6Icon from "./icons/PlasmicIcon__Polygon6"; // plasmic-import: 6YmzTPpOhex/icon
import FloresIcon from "./icons/PlasmicIcon__Flores"; // plasmic-import: kSeAGTBe8H7/icon
import Vector15Icon from "./icons/PlasmicIcon__Vector15"; // plasmic-import: 4N01F37ufcu/icon
import Vector16Icon from "./icons/PlasmicIcon__Vector16"; // plasmic-import: IxXbNq6loq8/icon
import Rings2Icon from "./icons/PlasmicIcon__Rings2"; // plasmic-import: z3BnojU3NyM/icon
import CopaIcon from "./icons/PlasmicIcon__Copa"; // plasmic-import: MCcUz9ZLVF1/icon
import CenaIcon from "./icons/PlasmicIcon__Cena"; // plasmic-import: PjrIv_sUJcV/icon
import BolaIcon from "./icons/PlasmicIcon__Bola"; // plasmic-import: bA8skHVm69t/icon
import WalletTracedIcon from "./icons/PlasmicIcon__WalletTraced"; // plasmic-import: ef38l5rGTjP/icon
import Ellipse1Icon from "./icons/PlasmicIcon__Ellipse1"; // plasmic-import: zGZjcbACVmL/icon
import TrazoMapa1TracedIcon from "./icons/PlasmicIcon__TrazoMapa1Traced"; // plasmic-import: vIB1zg7bYuR/icon
import UnionIcon from "./icons/PlasmicIcon__Union"; // plasmic-import: XF_eT3LVgni/icon
import RingsIcon from "./icons/PlasmicIcon__Rings"; // plasmic-import: 6Wz3Xy-RSTw/icon
import GasStationTracedIcon from "./icons/PlasmicIcon__GasStationTraced"; // plasmic-import: c2GIKsZ-vSG/icon
import vector2C2N1ZhuBzEz from "./images/vector2.svg"; // plasmic-import: C2n1zhuBzEz/picture
import vector3KiK5TbFXkxd from "./images/vector3.svg"; // plasmic-import: KiK5TbFXkxd/picture
import vector0NKdD7ATsPk from "./images/vector.svg"; // plasmic-import: 0NKdD7ATsPk/picture
import capturaDePantalla20220513ALas21151TracedHKAlucLm6Nq from "./images/capturaDePantalla20220513ALas21151Traced.svg"; // plasmic-import: hKAlucLm6Nq/picture
import placeholderGSsOKqN0I3 from "./images/placeholder.svg"; // plasmic-import: gSS-OKqN0I3/picture

export const PlasmicHomepage2__VariantProps = new Array();

export const PlasmicHomepage2__ArgProps = new Array();

function PlasmicHomepage2__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = Object.assign({}, props.args);
  const $props = args;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        {true ? (
          <div
            data-plasmic-name={"root"}
            data-plasmic-override={overrides.root}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              sty.root
            )}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"freeBox"}
              data-plasmic-override={overrides.freeBox}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox)}
            >
              <div
                data-plasmic-name={"figmaPaste"}
                data-plasmic-override={overrides.figmaPaste}
                className={classNames(projectcss.all, sty.figmaPaste)}
              >
                <div
                  data-plasmic-name={"home"}
                  data-plasmic-override={overrides.home}
                  className={classNames(projectcss.all, sty.home)}
                >
                  <div
                    data-plasmic-name={"whatsAppImage20220511At7541"}
                    data-plasmic-override={
                      overrides.whatsAppImage20220511At7541
                    }
                    className={classNames(
                      projectcss.all,
                      sty.whatsAppImage20220511At7541
                    )}
                  />

                  <div
                    data-plasmic-name={"fondo1"}
                    data-plasmic-override={overrides.fondo1}
                    className={classNames(projectcss.all, sty.fondo1)}
                  />

                  <div
                    data-plasmic-name={"fe5Ac4271Bc54Bf4940364Ce9Ed93A031"}
                    data-plasmic-override={
                      overrides.fe5Ac4271Bc54Bf4940364Ce9Ed93A031
                    }
                    className={classNames(
                      projectcss.all,
                      sty.fe5Ac4271Bc54Bf4940364Ce9Ed93A031
                    )}
                  />

                  <LetrasIcon
                    className={classNames(projectcss.all, sty.svg__fmAud)}
                    role={"img"}
                  />

                  <Group1Icon
                    className={classNames(projectcss.all, sty.svg___3Vpwk)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__o9JYw
                    )}
                  >
                    {"Nasim  &   Paul"}
                  </div>

                  {false ? (
                    <div
                      data-plasmic-name={"chicos1"}
                      data-plasmic-override={overrides.chicos1}
                      className={classNames(projectcss.all, sty.chicos1)}
                    />
                  ) : null}

                  <div
                    data-plasmic-name={"mask1"}
                    data-plasmic-override={overrides.mask1}
                    className={classNames(projectcss.all, sty.mask1)}
                  />
                </div>

                <div
                  data-plasmic-name={"frame3"}
                  data-plasmic-override={overrides.frame3}
                  className={classNames(projectcss.all, sty.frame3)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aquFi
                    )}
                  >
                    {"29 de Octubre 2022"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nzyWv
                    )}
                  >
                    {"00"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__m8Jsk
                    )}
                  >
                    {"00"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fo4EY
                    )}
                  >
                    {"00"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oiA1N
                    )}
                  >
                    {"00"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ww0Zu
                    )}
                  >
                    {"29 de Octubre 2022"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5ZjdY
                    )}
                  >
                    {"29 de Octubre 2022"}
                  </div>

                  <div
                    data-plasmic-name={"fincaMiravalleGuadarrama"}
                    data-plasmic-override={overrides.fincaMiravalleGuadarrama}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.fincaMiravalleGuadarrama
                    )}
                  >
                    {"Finca Miravalle, Guadarrama "}
                  </div>

                  <Polygon6Icon
                    className={classNames(projectcss.all, sty.svg__ozGlg)}
                    role={"img"}
                  />

                  <Polygon6Icon
                    className={classNames(projectcss.all, sty.svg__vgljI)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__x2W
                    )}
                  >
                    {"DÍAS"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jFcFc
                    )}
                  >
                    {"HORAS"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uvWs
                    )}
                  >
                    {"MINUTOS"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eoOil
                    )}
                  >
                    {"SEGUNDOS"}
                  </div>

                  <FloresIcon
                    className={classNames(projectcss.all, sty.svg__bXrt2)}
                    role={"img"}
                  />

                  <FloresIcon
                    className={classNames(projectcss.all, sty.svg__dI34N)}
                    role={"img"}
                  />
                </div>

                <div
                  data-plasmic-name={"frame2"}
                  data-plasmic-override={overrides.frame2}
                  className={classNames(projectcss.all, sty.frame2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ukNla
                    )}
                  >
                    {"Nuestra historia"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__feNfy
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lacus, dui malesuada vitae, eu semper morbi. Sit egestas sodales lectus cras est. Varius neque, malesuada sodales mattis turpis blandit duis tellus neque. Pretium porttitor et id phasellus laoreet tortor sagittis, duis. Nisl lacus, enim consequat, vitae, at nulla. Semper nisi, in est sollicitudin feugiat id malesuada elit rhoncus. Vestibulum, nec velit, feugiat est. Posuere ut varius elit nulla aliquam. Congue senectus in vestibulum tincidunt. Lorem orci et tortor in etiam ornare aliquam. Ultricies pretium rhoncus consequat molestie."
                    }
                  </div>

                  <div
                    data-plasmic-name={"layer11"}
                    data-plasmic-override={overrides.layer11}
                    className={classNames(projectcss.all, sty.layer11)}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__nbPfw)}
                    displayHeight={"215px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"169px"}
                    loading={"lazy"}
                    src={{
                      src: vector2C2N1ZhuBzEz,
                      fullWidth: 169,
                      fullHeight: 215,
                      aspectRatio: 0.786047
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__nfzMb)}
                    displayHeight={"215px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"169px"}
                    loading={"lazy"}
                    src={{
                      src: vector3KiK5TbFXkxd,
                      fullWidth: 169,
                      fullHeight: 215,
                      aspectRatio: 0.786047
                    }}
                  />
                </div>

                <div
                  data-plasmic-name={"frame4"}
                  data-plasmic-override={overrides.frame4}
                  className={classNames(projectcss.all, sty.frame4)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bDl4X
                    )}
                  >
                    {"¿Cómo va a ser \nnuestro día?"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qaTy
                    )}
                  >
                    {"00h"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lZxyx
                    )}
                  >
                    {"00h"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7D0Po
                    )}
                  >
                    {"00h"}
                  </div>

                  <Vector15Icon
                    className={classNames(projectcss.all, sty.svg__ofWQs)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ghEti
                    )}
                  >
                    {"Te podrás guapísimx"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gEwmM
                    )}
                  >
                    {"¡Nuesto momento!"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xLrGv
                    )}
                  >
                    {"Lorem sit ut nisl."}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__f0Win
                    )}
                  >
                    {
                      "Aprovechamos para decirte que nuestra boda será (estilo de la boda). Por lo que te recomenamos que te vistas...blablabla"
                    }
                  </div>

                  <div
                    data-plasmic-name={
                      "loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt"
                    }
                    data-plasmic-override={
                      overrides.loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Molestie leo nunc egestas viverra nullam pellentesque arcu sed at. "
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fBo6Q
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nibh euismod posuere ornare quis tempor enim in. Id suspendisse ligula amet."
                    }
                  </div>

                  <Vector16Icon
                    className={classNames(projectcss.all, sty.svg__cXomT)}
                    role={"img"}
                  />

                  <Vector16Icon
                    className={classNames(projectcss.all, sty.svg___7E8U)}
                    role={"img"}
                  />

                  <Vector16Icon
                    className={classNames(projectcss.all, sty.svg__niiNv)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1T6Xe
                    )}
                  >
                    {"00h"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ouxuK
                    )}
                  >
                    {"00h"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zvKyv
                    )}
                  >
                    {"00h"}
                  </div>

                  <div
                    data-plasmic-name={"yaEstarasAparcado"}
                    data-plasmic-override={overrides.yaEstarasAparcado}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.yaEstarasAparcado
                    )}
                  >
                    {"Ya estarás aparcado "}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__c2Np5
                    )}
                  >
                    {"Elit sit feugiat."}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__x1FQx
                    )}
                  >
                    {"Tincidunt purus."}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6HcQg
                    )}
                  >
                    {
                      "Tenemos X Plazas de coche disponibles así que llega puntual y no te pierdas nada......"
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pbuyK
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque fames sed eu ac."
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zUkl
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse tempor risus sed."
                    }
                  </div>

                  <Vector16Icon
                    className={classNames(projectcss.all, sty.svg___2QcHk)}
                    role={"img"}
                  />

                  <Vector16Icon
                    className={classNames(projectcss.all, sty.svg__j6Bp8)}
                    role={"img"}
                  />

                  <Vector16Icon
                    className={classNames(projectcss.all, sty.svg__z0Jfu)}
                    role={"img"}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__jReG7)}
                    displayHeight={"50px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"52px"}
                    loading={"lazy"}
                    src={{
                      src: vector0NKdD7ATsPk,
                      fullWidth: 52,
                      fullHeight: 50,
                      aspectRatio: 1.04
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__dcSiu)}
                    displayHeight={"39px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"46px"}
                    loading={"lazy"}
                    src={{
                      src: capturaDePantalla20220513ALas21151TracedHKAlucLm6Nq,
                      fullWidth: 46,
                      fullHeight: 39,
                      aspectRatio: 1.179487
                    }}
                  />

                  <Rings2Icon
                    className={classNames(projectcss.all, sty.svg___8SLn4)}
                    role={"img"}
                  />

                  <CopaIcon
                    className={classNames(projectcss.all, sty.svg___9Q61Q)}
                    role={"img"}
                  />

                  <CenaIcon
                    className={classNames(projectcss.all, sty.svg___53576)}
                    role={"img"}
                  />

                  <BolaIcon
                    className={classNames(projectcss.all, sty.svg__ngcvd)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"rama22"}
                    data-plasmic-override={overrides.rama22}
                    className={classNames(projectcss.all, sty.rama22)}
                  />

                  <div
                    data-plasmic-name={"rama23"}
                    data-plasmic-override={overrides.rama23}
                    className={classNames(projectcss.all, sty.rama23)}
                  />

                  <div
                    data-plasmic-name={"flor21"}
                    data-plasmic-override={overrides.flor21}
                    className={classNames(projectcss.all, sty.flor21)}
                  />

                  <div
                    data-plasmic-name={"flor22"}
                    data-plasmic-override={overrides.flor22}
                    className={classNames(projectcss.all, sty.flor22)}
                  />

                  <div
                    data-plasmic-name={"rama11"}
                    data-plasmic-override={overrides.rama11}
                    className={classNames(projectcss.all, sty.rama11)}
                  />

                  <div
                    data-plasmic-name={"rama12"}
                    data-plasmic-override={overrides.rama12}
                    className={classNames(projectcss.all, sty.rama12)}
                  />
                </div>

                <div
                  data-plasmic-name={"frame5"}
                  data-plasmic-override={overrides.frame5}
                  className={classNames(projectcss.all, sty.frame5)}
                />

                <div
                  data-plasmic-name={"frame6"}
                  data-plasmic-override={overrides.frame6}
                  className={classNames(projectcss.all, sty.frame6)}
                >
                  <div
                    data-plasmic-name={"rectangle33"}
                    data-plasmic-override={overrides.rectangle33}
                    className={classNames(projectcss.all, sty.rectangle33)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__iXwiy
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lacus, dui malesuada vitae, eu semper morbi. Sit egestas sodales lectus cras est. Varius neque, malesuada sodales mattis turpis blandit duis tellus neque. Pretium porttitor et id phasellus laoreet tortor sagittis, duis. Nisl lacus, enim consequat, vitae, at nulla. Semper nisi, in est sollicitudin feugiat id malesuada elit rhoncus. Vestibulum, nec velit, feugiat est. Posuere ut varius elit nulla aliquam. Congue senectus in vestibulum tincidunt. Lorem orci et tortor in etiam ornare aliquam. Ultricies pretium rhoncus consequat molestie."
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qsP9D
                    )}
                  >
                    {"Vuestras Palabras"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bZkt
                    )}
                  >
                    {"Ahmed & Ruth"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"frame7"}
                  data-plasmic-override={overrides.frame7}
                  className={classNames(projectcss.all, sty.frame7)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qysGt
                    )}
                  >
                    {"Ayúdanos a comenzar \nesta nueva etapa juntos"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__okSb
                    )}
                  >
                    {"0000 0000 0000 0000 0000"}
                  </div>

                  <WalletTracedIcon
                    className={classNames(projectcss.all, sty.svg__nS5L5)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__iJe6J
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lacus, dui malesuada vitae, eu semper morbi. Sit egestas sodales lectus cras est. Varius neque, malesuada sodales mattis turpis blandit duis tellus neque. Pretium porttitor et id phasellus laoreet tortor sagittis, duis. Nisl lacus, enim consequat, vitae, at nulla. Semper nisi, in est sollicitudin feugiat id malesuada elit rhoncus. Vestibulum, nec velit, feugiat est. Posuere ut varius elit nulla aliquam. Congue senectus in vestibulum tincidunt. Lorem orci et tortor in etiam ornare aliquam. Ultricies pretium rhoncus consequat molestie."
                    }
                  </div>
                </div>

                <div
                  data-plasmic-name={"frame8"}
                  data-plasmic-override={overrides.frame8}
                  className={classNames(projectcss.all, sty.frame8)}
                >
                  <div
                    data-plasmic-name={"creditCardForm"}
                    data-plasmic-override={overrides.creditCardForm}
                    className={classNames(projectcss.all, sty.creditCardForm)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__ePlqu)}
                      displayHeight={"203px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"220px"}
                      loading={"lazy"}
                      src={{
                        src: placeholderGSsOKqN0I3,
                        fullWidth: 220,
                        fullHeight: 203,
                        aspectRatio: 1.083744
                      }}
                    />

                    <div
                      data-plasmic-name={"middleDarkOutline"}
                      data-plasmic-override={overrides.middleDarkOutline}
                      className={classNames(
                        projectcss.all,
                        sty.middleDarkOutline
                      )}
                    >
                      <div
                        data-plasmic-name={"rectangle"}
                        data-plasmic-override={overrides.rectangle}
                        className={classNames(projectcss.all, sty.rectangle)}
                      />

                      <div
                        data-plasmic-name={"yourEmail"}
                        data-plasmic-override={overrides.yourEmail}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.yourEmail
                        )}
                      >
                        {""}
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"payPal"}
                      data-plasmic-override={overrides.payPal}
                      className={classNames(projectcss.all, sty.payPal)}
                    >
                      <div
                        data-plasmic-name={"useYourDebitOrCr"}
                        data-plasmic-override={overrides.useYourDebitOrCr}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.useYourDebitOrCr
                        )}
                      >
                        {"Use your debit or credit card to pay with PayPal"}
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"middleFill"}
                      data-plasmic-override={overrides.middleFill}
                      className={classNames(projectcss.all, sty.middleFill)}
                    >
                      <div
                        data-plasmic-name={"rectangle2"}
                        data-plasmic-override={overrides.rectangle2}
                        className={classNames(projectcss.all, sty.rectangle2)}
                      />

                      <div
                        data-plasmic-name={"signUp"}
                        data-plasmic-override={overrides.signUp}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.signUp
                        )}
                      >
                        {"Sign In"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___9Hyyh
                      )}
                    >
                      {"CVV"}
                    </div>

                    <div
                      data-plasmic-name={"middleDarkOutline2"}
                      data-plasmic-override={overrides.middleDarkOutline2}
                      className={classNames(
                        projectcss.all,
                        sty.middleDarkOutline2
                      )}
                    >
                      <div
                        data-plasmic-name={"rectangle3"}
                        data-plasmic-override={overrides.rectangle3}
                        className={classNames(projectcss.all, sty.rectangle3)}
                      />

                      <div
                        data-plasmic-name={"yourEmail2"}
                        data-plasmic-override={overrides.yourEmail2}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.yourEmail2
                        )}
                      >
                        {""}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ksmdd
                      )}
                    >
                      {"EXPIRATION"}
                    </div>

                    <div
                      data-plasmic-name={"middleDarkOutline3"}
                      data-plasmic-override={overrides.middleDarkOutline3}
                      className={classNames(
                        projectcss.all,
                        sty.middleDarkOutline3
                      )}
                    >
                      <div
                        data-plasmic-name={"rectangle4"}
                        data-plasmic-override={overrides.rectangle4}
                        className={classNames(projectcss.all, sty.rectangle4)}
                      />

                      <div
                        data-plasmic-name={"yourEmail3"}
                        data-plasmic-override={overrides.yourEmail3}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.yourEmail3
                        )}
                      >
                        {""}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jOnHa
                      )}
                    >
                      {"CARD NUMBER"}
                    </div>

                    <div
                      data-plasmic-name={"middleDarkOutline4"}
                      data-plasmic-override={overrides.middleDarkOutline4}
                      className={classNames(
                        projectcss.all,
                        sty.middleDarkOutline4
                      )}
                    >
                      <div
                        data-plasmic-name={"rectangle5"}
                        data-plasmic-override={overrides.rectangle5}
                        className={classNames(projectcss.all, sty.rectangle5)}
                      />

                      <div
                        data-plasmic-name={"yourEmail4"}
                        data-plasmic-override={overrides.yourEmail4}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.yourEmail4
                        )}
                      >
                        {""}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___1O00N
                      )}
                    >
                      {"Country"}
                    </div>

                    <div
                      data-plasmic-name={"middleDarkOutline5"}
                      data-plasmic-override={overrides.middleDarkOutline5}
                      className={classNames(
                        projectcss.all,
                        sty.middleDarkOutline5
                      )}
                    >
                      <div
                        data-plasmic-name={"rectangle6"}
                        data-plasmic-override={overrides.rectangle6}
                        className={classNames(projectcss.all, sty.rectangle6)}
                      />

                      <div
                        data-plasmic-name={"yourEmail5"}
                        data-plasmic-override={overrides.yourEmail5}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.yourEmail5
                        )}
                      >
                        {""}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jjMD
                      )}
                    >
                      {"City"}
                    </div>

                    <div
                      data-plasmic-name={"middleDarkOutline6"}
                      data-plasmic-override={overrides.middleDarkOutline6}
                      className={classNames(
                        projectcss.all,
                        sty.middleDarkOutline6
                      )}
                    >
                      <div
                        data-plasmic-name={"rectangle7"}
                        data-plasmic-override={overrides.rectangle7}
                        className={classNames(projectcss.all, sty.rectangle7)}
                      />

                      <div
                        data-plasmic-name={"yourEmail6"}
                        data-plasmic-override={overrides.yourEmail6}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.yourEmail6
                        )}
                      >
                        {""}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__iXoWu
                      )}
                    >
                      {"POSTAL / ZIP"}
                    </div>

                    <div
                      data-plasmic-name={"middleDarkOutline7"}
                      data-plasmic-override={overrides.middleDarkOutline7}
                      className={classNames(
                        projectcss.all,
                        sty.middleDarkOutline7
                      )}
                    >
                      <div
                        data-plasmic-name={"rectangle8"}
                        data-plasmic-override={overrides.rectangle8}
                        className={classNames(projectcss.all, sty.rectangle8)}
                      />

                      <div
                        data-plasmic-name={"yourEmail7"}
                        data-plasmic-override={overrides.yourEmail7}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.yourEmail7
                        )}
                      >
                        {""}
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"address"}
                      data-plasmic-override={overrides.address}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.address
                      )}
                    >
                      {"Address"}
                    </div>

                    <div
                      data-plasmic-name={"middleDarkOutline8"}
                      data-plasmic-override={overrides.middleDarkOutline8}
                      className={classNames(
                        projectcss.all,
                        sty.middleDarkOutline8
                      )}
                    >
                      <div
                        data-plasmic-name={"rectangle9"}
                        data-plasmic-override={overrides.rectangle9}
                        className={classNames(projectcss.all, sty.rectangle9)}
                      />

                      {false ? (
                        <div
                          data-plasmic-name={"yourEmail8"}
                          data-plasmic-override={overrides.yourEmail8}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.yourEmail8
                          )}
                        >
                          {"Shepovalov"}
                        </div>
                      ) : null}
                    </div>

                    <div
                      data-plasmic-name={"middleDarkOutline9"}
                      data-plasmic-override={overrides.middleDarkOutline9}
                      className={classNames(
                        projectcss.all,
                        sty.middleDarkOutline9
                      )}
                    >
                      <div
                        data-plasmic-name={"rectangle10"}
                        data-plasmic-override={overrides.rectangle10}
                        className={classNames(projectcss.all, sty.rectangle10)}
                      />

                      {false ? (
                        <div
                          data-plasmic-name={"yourEmail9"}
                          data-plasmic-override={overrides.yourEmail9}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.yourEmail9
                          )}
                        >
                          {"Denis"}
                        </div>
                      ) : null}
                    </div>

                    <div
                      data-plasmic-name={"expiration"}
                      data-plasmic-override={overrides.expiration}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.expiration
                      )}
                    >
                      {"Confirmacion de asistencia"}
                    </div>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fbYgg
                    )}
                  >
                    {"¿Vienes?"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bK5Q
                    )}
                  >
                    {
                      "Queremos que vengas a nuetra boda...\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Lacus, dui malesuada vitae, eu semper morbi. Sit egestas sodales lectus cras est. Varius neque, malesuada sodales mattis turpis blandit duis tellus neque. Pretium porttitor et id phasellus laoreet tortor sagittis, duis. Nisl lacus, enim consequat, vitae, at nulla. Semper nisi, in est sollicitudin feugiat id malesuada elit rhoncus. Vestibulum, nec velit, feugiat est. Posuere ut varius elit nulla aliquam. Congue senectus in vestibulum tincidunt. Lorem orci et tortor in etiam ornare aliquam. Ultricies pretium rhoncus consequat molestie."
                    }
                  </div>
                </div>

                <div
                  data-plasmic-name={"aboutFinal"}
                  data-plasmic-override={overrides.aboutFinal}
                  className={classNames(projectcss.all, sty.aboutFinal)}
                >
                  <div
                    data-plasmic-name={"map"}
                    data-plasmic-override={overrides.map}
                    className={classNames(projectcss.all, sty.map)}
                  >
                    <div
                      data-plasmic-name={"capturaDePantalla20220511ALas21131"}
                      data-plasmic-override={
                        overrides.capturaDePantalla20220511ALas21131
                      }
                      className={classNames(
                        projectcss.all,
                        sty.capturaDePantalla20220511ALas21131
                      )}
                    />

                    <Ellipse1Icon
                      className={classNames(projectcss.all, sty.svg__oixSg)}
                      role={"img"}
                    />

                    <TrazoMapa1TracedIcon
                      className={classNames(projectcss.all, sty.svg__mN9Pu)}
                      role={"img"}
                    />

                    <UnionIcon
                      className={classNames(projectcss.all, sty.svg__qx296)}
                      role={"img"}
                    />

                    <RingsIcon
                      className={classNames(projectcss.all, sty.svg___0MBpg)}
                      role={"img"}
                    />

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame9"}
                      data-plasmic-override={overrides.frame9}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame9)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___6M3Xh
                        )}
                      >
                        {"M-527"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame13"}
                      data-plasmic-override={overrides.frame13}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame13)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__eEAuY
                        )}
                      >
                        {"M-620"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame15"}
                      data-plasmic-override={overrides.frame15}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame15)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ekGuC
                        )}
                      >
                        {"M-510"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame14"}
                      data-plasmic-override={overrides.frame14}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame14)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tAl8D
                        )}
                      >
                        {"M-619"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame11"}
                      data-plasmic-override={overrides.frame11}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame11)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__q262J
                        )}
                      >
                        {"AP-6"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame12"}
                      data-plasmic-override={overrides.frame12}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame12)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fSvdT
                        )}
                      >
                        {"AP-6"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame10"}
                      data-plasmic-override={overrides.frame10}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame10)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jCtvg
                        )}
                      >
                        {"N-VI"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame16"}
                      data-plasmic-override={overrides.frame16}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame16)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jkaDk
                        )}
                      >
                        {"N-VI"}
                      </div>
                    </p.Stack>

                    <GasStationTracedIcon
                      className={classNames(projectcss.all, sty.svg__rIsgc)}
                      role={"img"}
                    />
                  </div>
                </div>

                <Polygon6Icon
                  className={classNames(projectcss.all, sty.svg__wh8Fx)}
                  role={"img"}
                />

                <Polygon6Icon
                  className={classNames(projectcss.all, sty.svg__wajMv)}
                  role={"img"}
                />
              </div>
            </p.Stack>
          </div>
        ) : null}
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "freeBox",
    "figmaPaste",
    "home",
    "whatsAppImage20220511At7541",
    "fondo1",
    "fe5Ac4271Bc54Bf4940364Ce9Ed93A031",
    "chicos1",
    "mask1",
    "frame3",
    "fincaMiravalleGuadarrama",
    "frame2",
    "layer11",
    "frame4",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt",
    "yaEstarasAparcado",
    "rama22",
    "rama23",
    "flor21",
    "flor22",
    "rama11",
    "rama12",
    "frame5",
    "frame6",
    "rectangle33",
    "frame7",
    "frame8",
    "creditCardForm",
    "middleDarkOutline",
    "rectangle",
    "yourEmail",
    "payPal",
    "useYourDebitOrCr",
    "middleFill",
    "rectangle2",
    "signUp",
    "middleDarkOutline2",
    "rectangle3",
    "yourEmail2",
    "middleDarkOutline3",
    "rectangle4",
    "yourEmail3",
    "middleDarkOutline4",
    "rectangle5",
    "yourEmail4",
    "middleDarkOutline5",
    "rectangle6",
    "yourEmail5",
    "middleDarkOutline6",
    "rectangle7",
    "yourEmail6",
    "middleDarkOutline7",
    "rectangle8",
    "yourEmail7",
    "address",
    "middleDarkOutline8",
    "rectangle9",
    "yourEmail8",
    "middleDarkOutline9",
    "rectangle10",
    "yourEmail9",
    "expiration",
    "aboutFinal",
    "map",
    "capturaDePantalla20220511ALas21131",
    "frame9",
    "frame13",
    "frame15",
    "frame14",
    "frame11",
    "frame12",
    "frame10",
    "frame16"
  ],

  freeBox: [
    "freeBox",
    "figmaPaste",
    "home",
    "whatsAppImage20220511At7541",
    "fondo1",
    "fe5Ac4271Bc54Bf4940364Ce9Ed93A031",
    "chicos1",
    "mask1",
    "frame3",
    "fincaMiravalleGuadarrama",
    "frame2",
    "layer11",
    "frame4",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt",
    "yaEstarasAparcado",
    "rama22",
    "rama23",
    "flor21",
    "flor22",
    "rama11",
    "rama12",
    "frame5",
    "frame6",
    "rectangle33",
    "frame7",
    "frame8",
    "creditCardForm",
    "middleDarkOutline",
    "rectangle",
    "yourEmail",
    "payPal",
    "useYourDebitOrCr",
    "middleFill",
    "rectangle2",
    "signUp",
    "middleDarkOutline2",
    "rectangle3",
    "yourEmail2",
    "middleDarkOutline3",
    "rectangle4",
    "yourEmail3",
    "middleDarkOutline4",
    "rectangle5",
    "yourEmail4",
    "middleDarkOutline5",
    "rectangle6",
    "yourEmail5",
    "middleDarkOutline6",
    "rectangle7",
    "yourEmail6",
    "middleDarkOutline7",
    "rectangle8",
    "yourEmail7",
    "address",
    "middleDarkOutline8",
    "rectangle9",
    "yourEmail8",
    "middleDarkOutline9",
    "rectangle10",
    "yourEmail9",
    "expiration",
    "aboutFinal",
    "map",
    "capturaDePantalla20220511ALas21131",
    "frame9",
    "frame13",
    "frame15",
    "frame14",
    "frame11",
    "frame12",
    "frame10",
    "frame16"
  ],

  figmaPaste: [
    "figmaPaste",
    "home",
    "whatsAppImage20220511At7541",
    "fondo1",
    "fe5Ac4271Bc54Bf4940364Ce9Ed93A031",
    "chicos1",
    "mask1",
    "frame3",
    "fincaMiravalleGuadarrama",
    "frame2",
    "layer11",
    "frame4",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt",
    "yaEstarasAparcado",
    "rama22",
    "rama23",
    "flor21",
    "flor22",
    "rama11",
    "rama12",
    "frame5",
    "frame6",
    "rectangle33",
    "frame7",
    "frame8",
    "creditCardForm",
    "middleDarkOutline",
    "rectangle",
    "yourEmail",
    "payPal",
    "useYourDebitOrCr",
    "middleFill",
    "rectangle2",
    "signUp",
    "middleDarkOutline2",
    "rectangle3",
    "yourEmail2",
    "middleDarkOutline3",
    "rectangle4",
    "yourEmail3",
    "middleDarkOutline4",
    "rectangle5",
    "yourEmail4",
    "middleDarkOutline5",
    "rectangle6",
    "yourEmail5",
    "middleDarkOutline6",
    "rectangle7",
    "yourEmail6",
    "middleDarkOutline7",
    "rectangle8",
    "yourEmail7",
    "address",
    "middleDarkOutline8",
    "rectangle9",
    "yourEmail8",
    "middleDarkOutline9",
    "rectangle10",
    "yourEmail9",
    "expiration",
    "aboutFinal",
    "map",
    "capturaDePantalla20220511ALas21131",
    "frame9",
    "frame13",
    "frame15",
    "frame14",
    "frame11",
    "frame12",
    "frame10",
    "frame16"
  ],

  home: [
    "home",
    "whatsAppImage20220511At7541",
    "fondo1",
    "fe5Ac4271Bc54Bf4940364Ce9Ed93A031",
    "chicos1",
    "mask1"
  ],

  whatsAppImage20220511At7541: ["whatsAppImage20220511At7541"],
  fondo1: ["fondo1"],
  fe5Ac4271Bc54Bf4940364Ce9Ed93A031: ["fe5Ac4271Bc54Bf4940364Ce9Ed93A031"],
  chicos1: ["chicos1"],
  mask1: ["mask1"],
  frame3: ["frame3", "fincaMiravalleGuadarrama"],
  fincaMiravalleGuadarrama: ["fincaMiravalleGuadarrama"],
  frame2: ["frame2", "layer11"],
  layer11: ["layer11"],
  frame4: [
    "frame4",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt",
    "yaEstarasAparcado",
    "rama22",
    "rama23",
    "flor21",
    "flor22",
    "rama11",
    "rama12"
  ],

  loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt:
    [
      "loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt"
    ],

  yaEstarasAparcado: ["yaEstarasAparcado"],
  rama22: ["rama22"],
  rama23: ["rama23"],
  flor21: ["flor21"],
  flor22: ["flor22"],
  rama11: ["rama11"],
  rama12: ["rama12"],
  frame5: ["frame5"],
  frame6: ["frame6", "rectangle33"],
  rectangle33: ["rectangle33"],
  frame7: ["frame7"],
  frame8: [
    "frame8",
    "creditCardForm",
    "middleDarkOutline",
    "rectangle",
    "yourEmail",
    "payPal",
    "useYourDebitOrCr",
    "middleFill",
    "rectangle2",
    "signUp",
    "middleDarkOutline2",
    "rectangle3",
    "yourEmail2",
    "middleDarkOutline3",
    "rectangle4",
    "yourEmail3",
    "middleDarkOutline4",
    "rectangle5",
    "yourEmail4",
    "middleDarkOutline5",
    "rectangle6",
    "yourEmail5",
    "middleDarkOutline6",
    "rectangle7",
    "yourEmail6",
    "middleDarkOutline7",
    "rectangle8",
    "yourEmail7",
    "address",
    "middleDarkOutline8",
    "rectangle9",
    "yourEmail8",
    "middleDarkOutline9",
    "rectangle10",
    "yourEmail9",
    "expiration"
  ],

  creditCardForm: [
    "creditCardForm",
    "middleDarkOutline",
    "rectangle",
    "yourEmail",
    "payPal",
    "useYourDebitOrCr",
    "middleFill",
    "rectangle2",
    "signUp",
    "middleDarkOutline2",
    "rectangle3",
    "yourEmail2",
    "middleDarkOutline3",
    "rectangle4",
    "yourEmail3",
    "middleDarkOutline4",
    "rectangle5",
    "yourEmail4",
    "middleDarkOutline5",
    "rectangle6",
    "yourEmail5",
    "middleDarkOutline6",
    "rectangle7",
    "yourEmail6",
    "middleDarkOutline7",
    "rectangle8",
    "yourEmail7",
    "address",
    "middleDarkOutline8",
    "rectangle9",
    "yourEmail8",
    "middleDarkOutline9",
    "rectangle10",
    "yourEmail9",
    "expiration"
  ],

  middleDarkOutline: ["middleDarkOutline", "rectangle", "yourEmail"],
  rectangle: ["rectangle"],
  yourEmail: ["yourEmail"],
  payPal: ["payPal", "useYourDebitOrCr"],
  useYourDebitOrCr: ["useYourDebitOrCr"],
  middleFill: ["middleFill", "rectangle2", "signUp"],
  rectangle2: ["rectangle2"],
  signUp: ["signUp"],
  middleDarkOutline2: ["middleDarkOutline2", "rectangle3", "yourEmail2"],
  rectangle3: ["rectangle3"],
  yourEmail2: ["yourEmail2"],
  middleDarkOutline3: ["middleDarkOutline3", "rectangle4", "yourEmail3"],
  rectangle4: ["rectangle4"],
  yourEmail3: ["yourEmail3"],
  middleDarkOutline4: ["middleDarkOutline4", "rectangle5", "yourEmail4"],
  rectangle5: ["rectangle5"],
  yourEmail4: ["yourEmail4"],
  middleDarkOutline5: ["middleDarkOutline5", "rectangle6", "yourEmail5"],
  rectangle6: ["rectangle6"],
  yourEmail5: ["yourEmail5"],
  middleDarkOutline6: ["middleDarkOutline6", "rectangle7", "yourEmail6"],
  rectangle7: ["rectangle7"],
  yourEmail6: ["yourEmail6"],
  middleDarkOutline7: ["middleDarkOutline7", "rectangle8", "yourEmail7"],
  rectangle8: ["rectangle8"],
  yourEmail7: ["yourEmail7"],
  address: ["address"],
  middleDarkOutline8: ["middleDarkOutline8", "rectangle9", "yourEmail8"],
  rectangle9: ["rectangle9"],
  yourEmail8: ["yourEmail8"],
  middleDarkOutline9: ["middleDarkOutline9", "rectangle10", "yourEmail9"],
  rectangle10: ["rectangle10"],
  yourEmail9: ["yourEmail9"],
  expiration: ["expiration"],
  aboutFinal: [
    "aboutFinal",
    "map",
    "capturaDePantalla20220511ALas21131",
    "frame9",
    "frame13",
    "frame15",
    "frame14",
    "frame11",
    "frame12",
    "frame10",
    "frame16"
  ],

  map: [
    "map",
    "capturaDePantalla20220511ALas21131",
    "frame9",
    "frame13",
    "frame15",
    "frame14",
    "frame11",
    "frame12",
    "frame10",
    "frame16"
  ],

  capturaDePantalla20220511ALas21131: ["capturaDePantalla20220511ALas21131"],
  frame9: ["frame9"],
  frame13: ["frame13"],
  frame15: ["frame15"],
  frame14: ["frame14"],
  frame11: ["frame11"],
  frame12: ["frame12"],
  frame10: ["frame10"],
  frame16: ["frame16"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage2__ArgProps,
      internalVariantPropNames: PlasmicHomepage2__VariantProps
    });

    return PlasmicHomepage2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage2";
  } else {
    func.displayName = `PlasmicHomepage2.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage2 = Object.assign(
  // Top-level PlasmicHomepage2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    figmaPaste: makeNodeComponent("figmaPaste"),
    home: makeNodeComponent("home"),
    whatsAppImage20220511At7541: makeNodeComponent(
      "whatsAppImage20220511At7541"
    ),

    fondo1: makeNodeComponent("fondo1"),
    fe5Ac4271Bc54Bf4940364Ce9Ed93A031: makeNodeComponent(
      "fe5Ac4271Bc54Bf4940364Ce9Ed93A031"
    ),

    chicos1: makeNodeComponent("chicos1"),
    mask1: makeNodeComponent("mask1"),
    frame3: makeNodeComponent("frame3"),
    fincaMiravalleGuadarrama: makeNodeComponent("fincaMiravalleGuadarrama"),
    frame2: makeNodeComponent("frame2"),
    layer11: makeNodeComponent("layer11"),
    frame4: makeNodeComponent("frame4"),
    loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt:
      makeNodeComponent(
        "loremIpsumDolorSitAmetConsecteturAdipiscingElitMolestieLeoNuncEgestasViverraNullamPellentesqueArcuSedAt"
      ),

    yaEstarasAparcado: makeNodeComponent("yaEstarasAparcado"),
    rama22: makeNodeComponent("rama22"),
    rama23: makeNodeComponent("rama23"),
    flor21: makeNodeComponent("flor21"),
    flor22: makeNodeComponent("flor22"),
    rama11: makeNodeComponent("rama11"),
    rama12: makeNodeComponent("rama12"),
    frame5: makeNodeComponent("frame5"),
    frame6: makeNodeComponent("frame6"),
    rectangle33: makeNodeComponent("rectangle33"),
    frame7: makeNodeComponent("frame7"),
    frame8: makeNodeComponent("frame8"),
    creditCardForm: makeNodeComponent("creditCardForm"),
    middleDarkOutline: makeNodeComponent("middleDarkOutline"),
    rectangle: makeNodeComponent("rectangle"),
    yourEmail: makeNodeComponent("yourEmail"),
    payPal: makeNodeComponent("payPal"),
    useYourDebitOrCr: makeNodeComponent("useYourDebitOrCr"),
    middleFill: makeNodeComponent("middleFill"),
    rectangle2: makeNodeComponent("rectangle2"),
    signUp: makeNodeComponent("signUp"),
    middleDarkOutline2: makeNodeComponent("middleDarkOutline2"),
    rectangle3: makeNodeComponent("rectangle3"),
    yourEmail2: makeNodeComponent("yourEmail2"),
    middleDarkOutline3: makeNodeComponent("middleDarkOutline3"),
    rectangle4: makeNodeComponent("rectangle4"),
    yourEmail3: makeNodeComponent("yourEmail3"),
    middleDarkOutline4: makeNodeComponent("middleDarkOutline4"),
    rectangle5: makeNodeComponent("rectangle5"),
    yourEmail4: makeNodeComponent("yourEmail4"),
    middleDarkOutline5: makeNodeComponent("middleDarkOutline5"),
    rectangle6: makeNodeComponent("rectangle6"),
    yourEmail5: makeNodeComponent("yourEmail5"),
    middleDarkOutline6: makeNodeComponent("middleDarkOutline6"),
    rectangle7: makeNodeComponent("rectangle7"),
    yourEmail6: makeNodeComponent("yourEmail6"),
    middleDarkOutline7: makeNodeComponent("middleDarkOutline7"),
    rectangle8: makeNodeComponent("rectangle8"),
    yourEmail7: makeNodeComponent("yourEmail7"),
    address: makeNodeComponent("address"),
    middleDarkOutline8: makeNodeComponent("middleDarkOutline8"),
    rectangle9: makeNodeComponent("rectangle9"),
    yourEmail8: makeNodeComponent("yourEmail8"),
    middleDarkOutline9: makeNodeComponent("middleDarkOutline9"),
    rectangle10: makeNodeComponent("rectangle10"),
    yourEmail9: makeNodeComponent("yourEmail9"),
    expiration: makeNodeComponent("expiration"),
    aboutFinal: makeNodeComponent("aboutFinal"),
    map: makeNodeComponent("map"),
    capturaDePantalla20220511ALas21131: makeNodeComponent(
      "capturaDePantalla20220511ALas21131"
    ),

    frame9: makeNodeComponent("frame9"),
    frame13: makeNodeComponent("frame13"),
    frame15: makeNodeComponent("frame15"),
    frame14: makeNodeComponent("frame14"),
    frame11: makeNodeComponent("frame11"),
    frame12: makeNodeComponent("frame12"),
    frame10: makeNodeComponent("frame10"),
    frame16: makeNodeComponent("frame16"),
    // Metadata about props expected for PlasmicHomepage2
    internalVariantProps: PlasmicHomepage2__VariantProps,
    internalArgProps: PlasmicHomepage2__ArgProps
  }
);

export default PlasmicHomepage2;
/* prettier-ignore-end */
